### ISSUE TITLE
unable to start/run Fallout NV error P:0000065635

### ISSUE THREAD

**Issue by Frambooisier** [rockerbacon/modorganizer2-linux-installer#318]
Hello,

I think I have set up everything up, and MO2 starts from steam correctly, trying to launch the game from there leads to Steam Error window "Application load error P:0000065635" despite not loading any mods. Launching the game through protontricks from the same folder seems to load the game properly but it crashes on intro anyway (dont think its a issue here)

MY system info
Opensuse Tumbleweed up-to-date
Fallout NV 22490
mo2installer-4_3_0

**Comment by RayCarver** [comment]
Have the same issue on the Linux Mint. It had some troubles installing Log folder or something like that. Maybe this is the problem. Have no mods still as well.

**Comment by Frambooisier** [comment]
Maybe I will try to redo the whole thing, if you figure it out remember to post it here :)

**Comment by RayCarver** [comment]
I have made some progress. By changing to the Fallout Launcher it just pops window saying that instance is already running. Prior error was fixed (?) or a new one showed/replaced the old one

**Comment by RayCarver** [comment]
No it was just more bugs on top. Carry on. The issue is still there

**Comment by RayCarver** [comment]
OK. Huge update. 4gb patcher fixes the problem. But the game cannot be launched in launcher, meaning i can't change settings. I think case with error might be closed. Just install a patcher. Error still happen in launcher, but the rest is working

**Comment by bran112299** [comment]
Still unable to open the launcher with post install prefix and be able to change my game settings with the 4gb patch
