### ISSUE TITLE
Simple problem that plagues me. Application Load Error 5

### ISSUE THREAD

**Issue by deane-c64** [rockerbacon/modorganizer2-linux-installer#588]
![image](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/69091380/57cffc73-d7ae-45b9-abe4-b2a5c680a045)

thats what comes up when trying to start the game, no matter what. Both New Vegas & Oblivion. Using flatpack version of steam. This ONLY happens with flatpack Steam. Does NOT happen with Debian packages!

**Comment by rockerbacon** [comment]
Install logs?

**Comment by femiurge** [comment]
I have been having the same issue, I am on OpenSuse Tumbleweed with flatpack steam and have tested this on a VM too.

**Comment by zbikk** [comment]
![image](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/145393776/66dac2c2-0c48-4d84-915a-99d7cbbcbddd)
i'm getting this one, ugh

**Comment by zbikk** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1349848987 ok it seems like it's a problem with the PCR version of new vegas, holy fuck i hate bethesda

**Comment by zbikk** [comment]
okay i fixed my issue by following this guide https://steamcommunity.com/sharedfiles/filedetails/?id=1349848987 and just replacing the launcher file.

**Comment by Proficiency-git** [comment]
Okay, similar problem happened to me, but first, install log:

>INFO: all dependencies met
INFO: selected game 'newvegas'
INFO: steam not found in ''
INFO: found Steam in '/home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: user confirmed prefix setup
INFO: selected install directory '/home/anggiar/Games/mod-organizer-2-newvegas'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: downloading 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z'
INFO: downloading 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: using wget backend
INFO: fetching remote resource at 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks'
INFO: downloading 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' to '/tmp/mo2-linux-installer-downloads-cache/winetricks'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/xNVSE/NVSE/releases/download/6.2.4/nvse_6_2_4.7z'
INFO: downloading 'https://github.com/xNVSE/NVSE/releases/download/6.2.4/nvse_6_2_4.7z' to '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4.7z'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4.7z' to '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4'
INFO: installing JDK in '/home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/drive_c/java'
INFO: installing Mod Organizer 2 in '/home/anggiar/Games/mod-organizer-2-newvegas/modorganizer2'
INFO: installing script extender in '/home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Fallout New Vegas'
INFO: copying all files from '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4' into '/home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Fallout New Vegas'
INFO: installing nxm link broker in '/home/anggiar/.local/share/modorganizer2'
INFO: installing nxm link handler in '/home/anggiar/.local/share/applications/'
INFO: applying protontricks d3dcompiler_43 d3dx9
steam-runtime-launcher-service[69]: W: The --socket option is deprecated. Prefer to use --session or --bus-name.
Using winetricks 20230212-next (protontricks) - sha256sum: 0101cf7982b23c0a25f615de9f33a5d8c7928addbf2f391c2fc6ee690634861e with wine-9.0 and WINEARCH=win64
                                                                  Executing w_do_call d3dcompiler_43
          Executing load_d3dcompiler_43 
                                        grep: warning: stray \ before /
                                                                       Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp -L -F *d3dcompiler_43*x86* /home/anggiar/.var/app/com.github.Matoking.protontricks/cache/winetricks/directx9/directx_Jun2010_redist.exe
                                                                                       Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dcompiler_43.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/jun2010_d3dcompiler_43_x86.cab
                                                             /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/jun2010_d3dcompiler_43_x86.cab: WARNING; possible 5960 extra bytes at end of file.
                                                                                       Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp -L -F *d3dcompiler_43*x64* /home/anggiar/.var/app/com.github.Matoking.protontricks/cache/winetricks/directx9/directx_Jun2010_redist.exe
             Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dcompiler_43.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/jun2010_d3dcompiler_43_x64.cab
                                                                             /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/jun2010_d3dcompiler_43_x64.cab: WARNING; possible 5960 extra bytes at end of file.
             Using native override for following DLLs: d3dcompiler_43
                                                                     Executing /home/anggiar/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton Experimental/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\override-dll.reg
                                                                             steam-runtime-launch-client[2856]: W: The --socket option is deprecated. Prefer to use the session bus.
/bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
fsync: up and running.
0070:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0070:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0070:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0070:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
Executing /home/anggiar/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton Experimental/bin/wine64 C:\windows\regedit.exe /S C:\windows\Temp\override-dll.reg
 steam-runtime-launch-client[2906]: W: The --socket option is deprecated. Prefer to use the session bus.
/bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
wineserver: using server-side synchronization.
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
Executing w_do_call d3dx9
                         Executing load_d3dx9 
                                              grep: warning: stray \ before /
                                                                             Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp -L -F *d3dx9*x86* /home/anggiar/.var/app/com.github.Matoking.protontricks/cache/winetricks/directx9/directx_Jun2010_redist.exe
                                                                                    Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/apr2005_d3dx9_25_x86.cab
                                            /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/apr2005_d3dx9_25_x86.cab: WARNING; possible 5960 extra bytes at end of file.
                                                                Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/apr2006_d3dx9_30_x86.cab
                        /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/apr2006_d3dx9_30_x86.cab: WARNING; possible 5960 extra bytes at end of file.
                                            Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/apr2007_d3dx9_33_x86.cab
    /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/apr2007_d3dx9_33_x86.cab: WARNING; possible 5960 extra bytes at end of file.
                        Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/aug2005_d3dx9_27_x86.cab
                                                                          /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/aug2005_d3dx9_27_x86.cab: WARNING; possible 5960 extra bytes at end of file.
    Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/aug2007_d3dx9_35_x86.cab
                                                      /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/aug2007_d3dx9_35_x86.cab: WARNING; possible 5960 extra bytes at end of file.
                                                                          Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/aug2008_d3dx9_39_x86.cab
                                  /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/aug2008_d3dx9_39_x86.cab: WARNING; possible 5960 extra bytes at end of file.
                                                      Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/aug2009_d3dx9_42_x86.cab
              /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/aug2009_d3dx9_42_x86.cab: WARNING; possible 5960 extra bytes at end of file.
                                  Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/dec2005_d3dx9_28_x86.cab
                                                                                    /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/dec2005_d3dx9_28_x86.cab: WARNING; possible 5960 extra bytes at end of file.
              Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/dec2006_d3dx9_32_x86.cab
                                                                /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/dec2006_d3dx9_32_x86.cab: WARNING; possible 5960 extra bytes at end of file.
                                                                                    Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/feb2005_d3dx9_24_x86.cab
                                            /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/feb2005_d3dx9_24_x86.cab: WARNING; possible 5960 extra bytes at end of file.
                                                                Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/feb2006_d3dx9_29_x86.cab
                        /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/feb2006_d3dx9_29_x86.cab: WARNING; possible 5960 extra bytes at end of file.
                                            Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/jun2005_d3dx9_26_x86.cab
    /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/jun2005_d3dx9_26_x86.cab: WARNING; possible 5960 extra bytes at end of file.
                        Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/jun2007_d3dx9_34_x86.cab
                                                                          /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/jun2007_d3dx9_34_x86.cab: WARNING; possible 5960 extra bytes at end of file.
    Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/jun2008_d3dx9_38_x86.cab
                                                      /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/jun2008_d3dx9_38_x86.cab: WARNING; possible 5960 extra bytes at end of file.
                                                                          Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/jun2010_d3dx9_43_x86.cab
                                  /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/jun2010_d3dx9_43_x86.cab: WARNING; possible 5960 extra bytes at end of file.
                                                      Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/mar2008_d3dx9_37_x86.cab
              /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/mar2008_d3dx9_37_x86.cab: WARNING; possible 5960 extra bytes at end of file.
                                  Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/mar2009_d3dx9_41_x86.cab
                                                                                    /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/mar2009_d3dx9_41_x86.cab: WARNING; possible 5960 extra bytes at end of file.
              Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/nov2007_d3dx9_36_x86.cab
                                                                /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/nov2007_d3dx9_36_x86.cab: WARNING; possible 5960 extra bytes at end of file.
                                                                                    Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/nov2008_d3dx9_40_x86.cab
                                            /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/nov2008_d3dx9_40_x86.cab: WARNING; possible 5960 extra bytes at end of file.
                                                                Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/oct2006_d3dx9_31_x86.cab
                        /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/oct2006_d3dx9_31_x86.cab: WARNING; possible 5960 extra bytes at end of file.
                                            Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp -L -F *d3dx9*x64* /home/anggiar/.var/app/com.github.Matoking.protontricks/cache/winetricks/directx9/directx_Jun2010_redist.exe
                                                   Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/apr2005_d3dx9_25_x64.cab
           /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/apr2005_d3dx9_25_x64.cab: WARNING; possible 5960 extra bytes at end of file.
                               Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/apr2006_d3dx9_30_x64.cab
                                                                                 /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/apr2006_d3dx9_30_x64.cab: WARNING; possible 5960 extra bytes at end of file.
           Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/apr2007_d3dx9_33_x64.cab
                                                             /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/apr2007_d3dx9_33_x64.cab: WARNING; possible 5960 extra bytes at end of file.
                                                                                 Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/aug2005_d3dx9_27_x64.cab
                                         /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/aug2005_d3dx9_27_x64.cab: WARNING; possible 5960 extra bytes at end of file.
                                                             Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/aug2007_d3dx9_35_x64.cab
                     /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/aug2007_d3dx9_35_x64.cab: WARNING; possible 5960 extra bytes at end of file.
                                         Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/aug2008_d3dx9_39_x64.cab
 /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/aug2008_d3dx9_39_x64.cab: WARNING; possible 5960 extra bytes at end of file.
                     Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/aug2009_d3dx9_42_x64.cab
                                                                       /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/aug2009_d3dx9_42_x64.cab: WARNING; possible 5960 extra bytes at end of file.
 Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/dec2005_d3dx9_28_x64.cab
                                                   /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/dec2005_d3dx9_28_x64.cab: WARNING; possible 5960 extra bytes at end of file.
                                                                       Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/dec2006_d3dx9_32_x64.cab
                               /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/dec2006_d3dx9_32_x64.cab: WARNING; possible 5960 extra bytes at end of file.
                                                   Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/feb2005_d3dx9_24_x64.cab
           /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/feb2005_d3dx9_24_x64.cab: WARNING; possible 5960 extra bytes at end of file.
                               Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/feb2006_d3dx9_29_x64.cab
                                                                                 /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/feb2006_d3dx9_29_x64.cab: WARNING; possible 5960 extra bytes at end of file.
           Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/jun2005_d3dx9_26_x64.cab
                                                             /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/jun2005_d3dx9_26_x64.cab: WARNING; possible 5960 extra bytes at end of file.
                                                                                 Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/jun2007_d3dx9_34_x64.cab
                                         /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/jun2007_d3dx9_34_x64.cab: WARNING; possible 5960 extra bytes at end of file.
                                                             Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/jun2008_d3dx9_38_x64.cab
                     /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/jun2008_d3dx9_38_x64.cab: WARNING; possible 5960 extra bytes at end of file.
                                         Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/jun2010_d3dx9_43_x64.cab
 /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/jun2010_d3dx9_43_x64.cab: WARNING; possible 5960 extra bytes at end of file.
                     Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/mar2008_d3dx9_37_x64.cab
                                                                       /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/mar2008_d3dx9_37_x64.cab: WARNING; possible 5960 extra bytes at end of file.
 Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/mar2009_d3dx9_41_x64.cab
                                                   /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/mar2009_d3dx9_41_x64.cab: WARNING; possible 5960 extra bytes at end of file.
                                                                       Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/nov2007_d3dx9_36_x64.cab
                               /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/nov2007_d3dx9_36_x64.cab: WARNING; possible 5960 extra bytes at end of file.
                                                   Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/nov2008_d3dx9_40_x64.cab
           /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/nov2008_d3dx9_40_x64.cab: WARNING; possible 5960 extra bytes at end of file.
                               Executing cabextract -q -d /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/oct2006_d3dx9_31_x64.cab
                                                                                 /home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/oct2006_d3dx9_31_x64.cab: WARNING; possible 5960 extra bytes at end of file.
           Using native override for following DLLs: d3dx9_24 d3dx9_25 d3dx9_26 d3dx9_27 d3dx9_28 d3dx9_29 d3dx9_30
                         Executing /home/anggiar/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton Experimental/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\override-dll.reg
                                 steam-runtime-launch-client[4414]: W: The --socket option is deprecated. Prefer to use the session bus.
/bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
fsync: up and running.
0070:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0070:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0070:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0070:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
Executing /home/anggiar/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton Experimental/bin/wine64 C:\windows\regedit.exe /S C:\windows\Temp\override-dll.reg
 steam-runtime-launch-client[4464]: W: The --socket option is deprecated. Prefer to use the session bus.
/bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
wineserver: using server-side synchronization.
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
Using native override for following DLLs: d3dx9_31 d3dx9_32 d3dx9_33 d3dx9_34 d3dx9_35 d3dx9_36 d3dx9_37
              Executing /home/anggiar/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton Experimental/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\override-dll.reg
                      steam-runtime-launch-client[4661]: W: The --socket option is deprecated. Prefer to use the session bus.
/bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
wineserver: using server-side synchronization.
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
Executing /home/anggiar/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton Experimental/bin/wine64 C:\windows\regedit.exe /S C:\windows\Temp\override-dll.reg
 steam-runtime-launch-client[4827]: W: The --socket option is deprecated. Prefer to use the session bus.
/bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
wineserver: using server-side synchronization.
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
Using native override for following DLLs: d3dx9_38 d3dx9_39 d3dx9_40 d3dx9_41 d3dx9_42 d3dx9_43
     Executing /home/anggiar/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton Experimental/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\override-dll.reg
             steam-runtime-launch-client[4994]: W: The --socket option is deprecated. Prefer to use the session bus.
/bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
wineserver: using server-side synchronization.
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
Executing /home/anggiar/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton Experimental/bin/wine64 C:\windows\regedit.exe /S C:\windows\Temp\override-dll.reg
 steam-runtime-launch-client[5189]: W: The --socket option is deprecated. Prefer to use the session bus.
/bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
wineserver: using server-side synchronization.
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
INFO: configuring mo2 executable path 'Z:\home\anggiar\Games\mod-organizer-2-newvegas\modorganizer2\ModOrganizer.exe' in '/home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Fallout New Vegas/modorganizer2/instance_path.txt'
INFO: backing up original executable '/home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Fallout New Vegas/FalloutNVLauncher.exe' in '/home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Fallout New Vegas/_FalloutNVLauncher.exe'
INFO: setting up redirector in '/home/anggiar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Fallout New Vegas/FalloutNVLauncher.exe'
INFO: installation completed successfully

Had to allow every single file permission for Steam via Flatseal so that the launcher could launch.

And then when I clicked play, no error message:

![image](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/107824524/76716aa6-14e6-4e65-87f7-6a86f43119ee)

Also I've replaced the nvse. No dice.

**Comment by sdmichalak** [comment]
I had the same problem with PCR version and fixed it by restarting Steam and leaving `FalloutNVLauncher.exe` in MO2 as it was (basically skipping the post-install step) and adding `-appid 22490` argument to the `nvse_loader.exe`:
![obraz](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/91223938/ec1ff63d-01cb-4334-916c-2b96783d9508)
Also I've upgraded xNVSE (https://github.com/xNVSE/NVSE) and while I don't know if this step was related to fixing the issue, the game and NVSE itself works after launching NVSE from MO2.

**Comment by rockerbacon** [comment]
NVSE has been updated in a recent release. Can affected users confirm this is still a problem with the new NVSE?
If yes, can users confirm whether the additional nvse_loader arguments mentioned above fix the problem?

**Comment by sdmichalak** [comment]
I can confirm that it is fixed for me on a clean installation of the newest release.

**Comment by rockerbacon** [comment]
Closing as completed in #634
